INSERT INTO bears (name, age, gender, color, temperament, alive) VALUES ("Mr.Chocolate", 22, "Male", "Blue","Happy", True);
INSERT INTO bears (name, age, gender, color, temperament, alive) VALUES ("Rowdy", 24, "Male", "Yellow","Angry", True);
INSERT INTO bears (name, age, gender, color, temperament, alive) VALUES ("Tabitha", 22, "Male", "Blue","Happy", False);
INSERT INTO bears (name, age, gender, color, temperament, alive) VALUES ("Mr.Chocolate", 22, "Male", "Blue","Happy", True);
INSERT INTO bears (name, age, gender, color, temperament, alive) VALUES ("Mr.Chocolate", 22, "Male", "Blue","Happy", True);
INSERT INTO bears (name, age, gender, color, temperament, alive) VALUES ("Mr.Chocolate", 22, "Male", "Blue","Happy", True);
INSERT INTO bears (name, age, gender, color, temperament, alive) VALUES ("Mr.Chocolate", 22, "Male", "Blue","Happy", True);
INSERT INTO bears (name, age, gender, color, temperament, alive) VALUES ("Mr.Chocolate", 22, "Male", "Blue","Happy", True);
INSERT INTO bears (name, age, gender, color, temperament, alive) VALUES ("Mr.Chocolate", 22, "Male", "Blue","Happy", True);
